num_blocks: 12
embedding_dim: 512
input_patch_size: 32
output_patch_size: 32
input_ff_dim: 2048
h_expand: 4
context_len: 2048
future_len: 320
dropout: 0.1
quantiles:
- 0.1
- 0.2
- 0.3
- 0.4
- 0.5
- 0.6
- 0.7
- 0.8
- 0.9
act_func: torch.nn.SiLU
use_qk_norm: true
tokenizer_cfg:
  input_patch_size: 32
  output_patch_size: 32
  input_patch_stride: 32
scaler_cfg:
  use_arcsinh: true
  binaryaware: true
stack_out_norm_config:
  eps: 1.0e-07
tta_diff: true
stack_config:
  templates:
    slstm_attn:
      time_mixer:
        model_type: bi-slstm
        embedding_dim: 512
        num_heads: 4
        rnn_backend: flashrnn-cuda
        num_slstm_heads: 4
      variate_mixer:
        embedding_dim: 512
        num_heads: 4
      dropout: 0.1
      eps: 1.0e-07
    mlstm_attn:
      time_mixer:
        model_type: bi-mlstm
        embedding_dim: 512
        num_heads: 4
        rnn_backend: flashrnn-cuda
      variate_mixer:
        embedding_dim: 512
        num_heads: 4
      dropout: 0.1
      eps: 1.0e-07
  recipe:
  - mlstm_attn
  - slstm_attn
  - mlstm_attn
  - slstm_attn
  - mlstm_attn
  - slstm_attn
  - mlstm_attn
  - slstm_attn
  - mlstm_attn
  - slstm_attn
  - mlstm_attn
  - slstm_attn
